// Code generated by "stringer -type=TokenType,OptionalType,InstrFormat"; DO NOT EDIT.

package rvcore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INSTRUCTION-0]
	_ = x[OPERAND-1]
	_ = x[DIRECTIVE-2]
	_ = x[LABEL-3]
	_ = x[COMMA-4]
}

const _TokenType_name = "INSTRUCTIONOPERANDDIRECTIVELABELCOMMA"

var _TokenType_index = [...]uint8{0, 11, 18, 27, 32, 37}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLACEHOLDER-0]
	_ = x[IMMEDIATEINT-1]
	_ = x[IMMEDIATEHEX-2]
	_ = x[IMMEDIATEBYT-3]
	_ = x[REGISTER-4]
	_ = x[UNDEFINED-5]
}

const _OptionalType_name = "PLACEHOLDERIMMEDIATEINTIMMEDIATEHEXIMMEDIATEBYTREGISTERUNDEFINED"

var _OptionalType_index = [...]uint8{0, 11, 23, 35, 47, 55, 64}

func (i OptionalType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OptionalType_index)-1 {
		return "OptionalType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptionalType_name[_OptionalType_index[idx]:_OptionalType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNDEFINEDINSTR-0]
	_ = x[RTYPE-1]
	_ = x[ITYPE-2]
	_ = x[STYPE-3]
	_ = x[BTYPE-4]
	_ = x[UTYPE-5]
	_ = x[JTYPE-6]
}

const _InstrFormat_name = "UNDEFINEDINSTRRTYPEITYPESTYPEBTYPEUTYPEJTYPE"

var _InstrFormat_index = [...]uint8{0, 14, 19, 24, 29, 34, 39, 44}

func (i InstrFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_InstrFormat_index)-1 {
		return "InstrFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstrFormat_name[_InstrFormat_index[idx]:_InstrFormat_index[idx+1]]
}
